const PRODUCTS=['k101','k102','k106','k111','k111f','k113','k122','k131','k132','k201','k202','k203','k213','k301','k302'];
const app=document.getElementById('app');
const titleCase=x=>x.toUpperCase();
const product=(code)=>({code,name:`Product ${titleCase(code)}`,description:'Designed for everyday use, this versatile pouch is perfect for organizing and carrying your essentials. Made with quality materials, it offers a neat and compact design while providing sufficient space for your daily accessories.',category:'Product',availability:'Available'});
function nav(){return `<header class="nav"><div class="nav-inner"><a class="brand" href="/catalog">Kajal Enterprises</a><a class="nav-link" href="/catalog">Catalog</a></div></header>`}
function image(code,detail=false){const src=`assets/products/${code}.jpg`;return `<div class="${detail?'detail-image':'image'}"><img src="${src}" alt="${titleCase(code)}" onerror="this.style.display='none';this.parentElement.innerHTML='<span>${titleCase(code)}</span>'"></div>`}
function footer(){return `<footer><div class="container">© ${new Date().getFullYear()} Kajal Enterprises · Product Catalog</div></footer>`}
function catalog(){return `${nav()}<main><section class="hero container"><div class="eyebrow">Kajal Enterprises</div><h1>Product Catalog</h1><p>Browse our products by product code. Select any product to open its dedicated product page.</p></section><section class="container"><div class="toolbar"><input id="search" class="search" placeholder="Search product code…" autocomplete="off"><div id="count" class="count"></div></div><div id="grid" class="grid"></div></section></main>${footer()}`}
function renderGrid(q=''){const items=PRODUCTS.filter(x=>x.includes(q.toLowerCase()));document.getElementById('grid').innerHTML=items.length?items.map(c=>`<a class="card" href="/${c}">${image(c)}<div class="info"><div class="code">${c.toUpperCase()}</div><div class="name">Product ${c.toUpperCase()}</div><div class="view">View product →</div></div></a>`).join(''):`<p style="color:var(--muted)">No products found.</p>`;document.getElementById('count').textContent=`${items.length} product${items.length!==1?'s':''}`}
function detail(code){const p=product(code);return `${nav()}<main class="detail container"><a class="back" href="/catalog">← Back to catalog</a><div class="detail-layout">${image(code,true)}<section><div class="detail-code">PRODUCT CODE · ${p.code.toUpperCase()}</div><h1>${p.name}</h1><p class="detail-copy">${p.description}</p><div class="specs"><div class="spec"><span>Product code</span><strong>${p.code.toUpperCase()}</strong></div><div class="spec"><span>Category</span><strong>${p.category}</strong></div><div class="spec"><span>Availability</span><strong>${p.availability}</strong></div></div></section></div></main>${footer()}`}
function route(){let path=location.pathname.replace(/^\/+|\/+$/g,'').toLowerCase();if(path===''||path==='catalog'){app.innerHTML=catalog();renderGrid();document.getElementById('search').addEventListener('input',e=>renderGrid(e.target.value));return}if(PRODUCTS.includes(path)){app.innerHTML=detail(path);return}app.innerHTML=catalog();renderGrid();}
route();
